# Generated by Django 3.2.7 on 2021-09-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='value',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='value',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
